# this is for similar behaviour in python 2 and python 3 
from __future__ import print_function 
from numbers import Number 

@takes(Number, str) 
def f(a, b): 
    print(a, b) 

try: 
    f(1, 'abcd') 
except Exception as e:
    print(type(e).__name__) 

# comparison with type() does not take inheritance into account 
# use isinstance instead
